### ISSUE TITLE
Online pupil position tracking (SLEAP)

### ISSUE THREAD

**Issue by RoboDoig** [neurogears/vestibular-vr#25]
NGR will provide resources and pointers on the training labeling phase. 

We need to implement SLEAP tracking and logging in the current experiment workflow using a model trained by Ede's lab.

**Comment by RoboDoig** [comment]
To be able to train a useful SLEAP model, we need example pupil video data with some eye movements. To that end, need a workflow that generates a moving grating stimulus, e.g. sinusoidal movement of gratings in a virtual cylinder.

**Comment by EleonoraAmbrad** [comment]
videos for sleep training were sent via email (link to google drive). We are training the model on our end as well

**Comment by RoboDoig** [comment]
For implementation of online SLEAP tracking, setup instructions can be found here: https://bonsai-rx.org/sleap/

For exporting models: https://sleap.ai/guides/cli.html?highlight=export#sleap-export

Initial step would be to run a minimal workflow with SLEAP tracking on a prerecorded video to test the model. Next would be to add this to the main workflow with logging of tracked components.

**Comment by EleonoraAmbrad** [comment]
![Image](https://github.com/user-attachments/assets/cc4ba5e3-a277-4144-af63-39442155fa2a)

While I get an error due to a missing Path, I also get the message above from the command line. i guess the GPU is correctly detected. However would love some help for debugging as I am not sure how to implement the inference on a previously recorded video. I have been working on the "sleap-test.bonsai" workflow on the branch "nora-sleap-test".  Thanks!

**Comment by EleonoraAmbrad** [comment]
update: I just saw I left the training config empty, will test later

**Comment by EleonoraAmbrad** [comment]
Bonsai.WorkflowRuntimeException: 2 root error(s) found.
  (0) INVALID_ARGUMENT: ConcatOp : Dimension 2 in both shapes must be equal: shape[0] = [1,128,56,76] vs. shape[1] = [1,256,38,38]
	 [[{{node StatefulPartitionedCall/StatefulPartitionedCall/single_instance_inference_model_1/single_instance_inference_layer_1/model/stack0_dec0_s16_to_s8_skip_concat/concat}}]]
	 [[Identity/_47]]
  (1) INVALID_ARGUMENT: ConcatOp : Dimension 2 in both shapes must be equal: shape[0] = [1,128,56,76] vs. shape[1] = [1,256,38,38]
	 [[{{node StatefulPartitionedCall/StatefulPartitionedCall/single_instance_inference_model_1/single_instance_inference_layer_1/model/stack0_dec0_s16_to_s8_skip_concat/concat}}]]
0 successful operations.
0 derived errors ignored. ---> TensorFlow.TFException: 2 root error(s) found.
  (0) INVALID_ARGUMENT: ConcatOp : Dimension 2 in both shapes must be equal: shape[0] = [1,128,56,76] vs. shape[1] = [1,256,38,38]
	 [[{{node StatefulPartitionedCall/StatefulPartitionedCall/single_instance_inference_model_1/single_instance_inference_layer_1/model/stack0_dec0_s16_to_s8_skip_concat/concat}}]]
	 [[Identity/_47]]
  (1) INVALID_ARGUMENT: ConcatOp : Dimension 2 in both shapes must be equal: shape[0] = [1,128,56,76] vs. shape[1] = [1,256,38,38]
	 [[{{node StatefulPartitionedCall/StatefulPartitionedCall/single_instance_inference_model_1/single_instance_inference_layer_1/model/stack0_dec0_s16_to_s8_skip_concat/concat}}]]
0 successful operations.
0 derived errors ignored.
   at TensorFlow.TFStatus.CheckMaybeRaise(TFStatus incomingStatus, Boolean last)
   at TensorFlow.TFSession.Run(TFOutput[] inputs, TFTensor[] inputValues, TFOutput[] outputs, TFOperation[] targetOpers, TFBuffer runMetadata, TFBuffer runOptions, TFStatus status)
   at TensorFlow.TFSession.Runner.Run(TFStatus status)
   at Bonsai.Sleap.PredictSinglePose.<>c__DisplayClass20_1.<Process>b__1(IplImage[] input)
   at System.Reactive.Linq.ObservableImpl.Select`2._.OnNext(TSource value)
   --- End of inner exception stack trace ---


after some fiddling, I get this new error

**Comment by EleonoraAmbrad** [comment]
https://github.com/orgs/bonsai-rx/discussions/1532

I tried to retrain a top down model and use the PredictPoses node, when doing that I ran into the same error mentioned in this issue. I wonder if then the tensorflow installation is faulty. I am unsure how to pip install tensor flow from the ONIX computer, though

**Comment by EleonoraAmbrad** [comment]
just some updates from my side to keep track of development:

when tryin to run sleap inference from ONIX PC I ran into memory errors from the GPU. I ran the   tf.config.experimental.set_memory_growth(physical_devices[0], True) command and it seems to do the trick for SLEAP labeling. Bonsai still does not work because it relies on the tensorflow.dll that is pasted in the extensions folder, which has nothing to do with the one from the SLEAP environment.

**Comment by RoboDoig** [comment]
Discovered today that the main issue seems to be video size. One of the models was trained with a 300x300 input size which I missed and we were therefore getting input dimension errors when trying to run it on the standard 600x448. Since all the data seems to be 600x448, recommend training a new model with this explicit input shape. Will ask @EleonoraAmbrad to point me to some training videos and the points that need to be tracked and I'll generate a new model.

**Comment by RoboDoig** [comment]
Working model added with PR #131 - will add online inference and logging to the main workflow next.
